services:
  - type: web
    name: springboot-app
    runtime: java11
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
